// <auto-generated />
namespace Diplomado_Web_MVC_Consultorio_Medico.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ConsultorioDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConsultorioDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202001281459168_ConsultorioDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
